version: '3'

services:
    dns:
        build: ./bind
        image: dns
        ports:
            - 53:53/udp
            - 53:53/tcp
        volumes:
            - ./bind/conf:/etc/bind
        container_name: docker_dns
        restart: always
        networks:
            vpcbr:
                ipv4_address: 192.201.102.2
    web:
        build: ./apache
        image: web
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - ./apache/localhost:/var/www/localhost/htdocs
            - ./apache/iznv.com:/var/www/iznv.com/htdocs
            - ./apache/conf/httpd.conf:/etc/apache2/httpd.conf
            - ./apache/conf/vhosts.conf:/etc/apache2/conf.d/vhosts.conf
        container_name: docker_web
        restart: always
        networks:
            vpcbr:
                ipv4_address: 192.201.102.3
networks:
    vpcbr:
        ipam:
            config:
                - subnet: 192.201.102.0/24
